### ISSUE TITLE
Condition Block sidebar options

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wp-conditional-blocks#16]
### Description

The user should be able to select the condition they want to apply to the block in the sidebar using the information provided by the REST endpoint created in #14 

### Use Case

The user should be able to select the condition they want to apply to the block in the sidebar based on the available registered conditions.

### Acceptance Criteria

- Add a sidebar option to select the condition that applies to the block.
- Conditions must come from the REST API endpoint created in #14 
- The condition is saved to the block attributes
- The condition does not need to take effect on the front-end yet - that is handled in #17 
- Use [Block context](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-context/) too pass data to the child blocks.

**Comment by rpasillas** [comment]
This has been closed as part of #18.

**Comment by rpasillas** [comment]
Apparently the block context is not reliable and should be removed from the AC for this issue after speaking with Jake.
