### ISSUE TITLE
Add some basic conditions to the plugin

### ISSUE THREAD

**Issue by mogmarsh** [alleyinteractive/wp-conditional-blocks#18]
### Description

We should ship the plugin with some basic conditions included.

### Use Case

there should be some functionality without any customizations

### Acceptance Criteria

- Add support for some default conditions to start:
- `is_home`
- `is_single`
- `is_archive`
- `is_search`
- Determining if an item is the first in a list of items, such as in a Query Loop block, via a post template.

**Comment by jakewrfoster** [comment]
@mogmarsh #75 is ready for review
